// Generated by ui-preview/scripts/embed-device-assets.mjs. Do not edit manually.
#pragma once

#if defined(WALKIE_UI_DEMO)

#include "audio_loop.h"

#include <cstddef>
#include <cstdint>

namespace stopwatch {

struct UiAsset {
    const uint8_t* data;
    size_t size;
};

UiAsset uiAssetFor(DeviceState state);

}  // namespace stopwatch

#endif
